"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ReclaimMigratedBackingRequest(google.protobuf.message.Message):
    """ReclaimMigratedBackingRequest selects the topic to reclaim."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOPIC_FIELD_NUMBER: builtins.int
    DELETE_UNREFERENCED_FIELD_NUMBER: builtins.int
    topic: builtins.str
    'The Kafka topic whose leftover tiered-storage backing objects should be\n    reclaimed. Must be a fully migrated (cut-over) cloud topic.\n    '
    delete_unreferenced: builtins.bool
    'When false (the default) the request is a dry run: it reports the\n    objects it would delete without modifying the bucket. When true it\n    deletes the unreferenced backing objects, which additionally requires\n    the topic property `redpanda.cloud_topic.preserve_migrated_ts` to be\n    disabled.\n    '

    def __init__(self, *, topic: builtins.str=..., delete_unreferenced: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['delete_unreferenced', b'delete_unreferenced', 'topic', b'topic']) -> None:
        ...
Global___ReclaimMigratedBackingRequest: typing_extensions.TypeAlias = ReclaimMigratedBackingRequest

@typing.final
class PartitionReclaim(google.protobuf.message.Message):
    """PartitionReclaim is the per-partition breakdown of a reclaim sweep."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITION_FIELD_NUMBER: builtins.int
    START_OFFSET_FIELD_NUMBER: builtins.int
    SEGMENTS_SCANNED_FIELD_NUMBER: builtins.int
    SEGMENTS_REFERENCED_FIELD_NUMBER: builtins.int
    SEGMENTS_UNREFERENCED_FIELD_NUMBER: builtins.int
    OBJECTS_DELETED_FIELD_NUMBER: builtins.int
    SAMPLE_OBJECT_KEYS_FIELD_NUMBER: builtins.int
    partition: builtins.int
    'Partition id.'
    start_offset: builtins.int
    "The partition's live L1 start offset (a Kafka offset). Manifest segments\n    whose next offset is at or below this are no longer referenced.\n    "
    segments_scanned: builtins.int
    'Segments enumerated from the frozen tiered-storage manifest and its\n    spillover manifests.\n    '
    segments_referenced: builtins.int
    'Segments still referenced by the live cloud topic; left in place for\n    ordinary L1 garbage collection.\n    '
    segments_unreferenced: builtins.int
    'Unreferenced segments eligible for reclaim.'
    objects_deleted: builtins.int
    'Backing objects deleted (segment plus its `.tx` and `.index` siblings per\n    unreferenced segment). Zero on a dry run.\n    '

    @property
    def sample_object_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """A capped sample of the backing object keys that were (or, on a dry run,
        would be) deleted, for operator inspection.
        """

    def __init__(self, *, partition: builtins.int=..., start_offset: builtins.int=..., segments_scanned: builtins.int=..., segments_referenced: builtins.int=..., segments_unreferenced: builtins.int=..., objects_deleted: builtins.int=..., sample_object_keys: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['objects_deleted', b'objects_deleted', 'partition', b'partition', 'sample_object_keys', b'sample_object_keys', 'segments_referenced', b'segments_referenced', 'segments_scanned', b'segments_scanned', 'segments_unreferenced', b'segments_unreferenced', 'start_offset', b'start_offset']) -> None:
        ...
Global___PartitionReclaim: typing_extensions.TypeAlias = PartitionReclaim

@typing.final
class ReclaimMigratedBackingResponse(google.protobuf.message.Message):
    """ReclaimMigratedBackingResponse summarizes the sweep across all partitions."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DELETED_FIELD_NUMBER: builtins.int
    PARTITIONS_FIELD_NUMBER: builtins.int
    deleted: builtins.bool
    'Whether objects were actually deleted. False on a dry run.'

    @property
    def partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PartitionReclaim]:
        """Per-partition reclaim breakdown."""

    def __init__(self, *, deleted: builtins.bool=..., partitions: collections.abc.Iterable[Global___PartitionReclaim] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['deleted', b'deleted', 'partitions', b'partitions']) -> None:
        ...
Global___ReclaimMigratedBackingResponse: typing_extensions.TypeAlias = ReclaimMigratedBackingResponse